aws_region = "us-east-1"
project = "ci-cd-simple"
vpc_cidr = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
allowed_ssh_cidr = "IP/32" 
instance_type = "t3a.small"
key_pair_name = "" 
app_docker_image = "yourdockerhubuser/static-site:latest"
